GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/setup.py:200: UserWarning: MPS available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='mps', devices=1)`.
  rank_zero_warn(
  | Name    | Type             | Params
---------------------------------------------
0 | model   | GVP_GNN          | 893 K
1 | loss_fn | CrossEntropyLoss | 0
---------------------------------------------
893 K     Trainable params
0         Non-trainable params
893 K     Total params
3.575     Total estimated model params size (MB)
/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Traceback (most recent call last):
  File "main.py", line 212, in <module>
    main()
  File "main.py", line 209, in main
    train(args)
  File "main.py", line 193, in train
    trainer.fit(model, train_dataloader, val_dataloader)
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1485, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/Users/antoniaboca/miniconda3/envs/diss-python3.8/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
TypeError: validation_step() takes 2 positional arguments but 3 were given
Start training...
Sanity Checking DataLoader 0:   0%|                                                                                                                                                                                    | 0/2 [00:00<?, ?it/s]